### ISSUE TITLE
README doesn't get the project running for me

### ISSUE THREAD

**Issue by trptcolin** [esmevane/duckling#5]
Putting on my client hat here: I can't get the project to run.

I tried what was in the README:
```
colin:duckling/ (master) $ java ./duckling.jar
Error: Could not find or load main class ..duckling.jar
colin:duckling/ (master) $ ls -l ./duckling.jar
ls: ./duckling.jar: No such file or directory
```

Also tried building the jar myself:
```
colin:duckling/ (master) $ ./gradlew test
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

Didn't go beyond there in terms of research - what's the best way to get this running on my machine?

**Comment by esmevane** [comment]
Thanks for this!  I've got two major ways to resolve this.

In the short-term, the [v0.0.1 release](https://github.com/esmevane/duckling/releases/tag/v0.0.1)  has a `duckling.jar` bundled.  I can immediately update the README to point there.

In the long term, I'll get a build system established and get that in the README as well.

**Comment by esmevane** [comment]
Language improved in https://github.com/esmevane/duckling/pull/7 - a simple local build system is coming up in the next few days.

**Comment by esmevane** [comment]
Or, immediately!  https://github.com/esmevane/duckling/pull/8 has a build system and an expanded README.  

Let me know if this resolves things for you.  :)

**Comment by RadicalZephyr** [comment]
I think I may have steered you wrong on this one.  I think you need to put the `gradle` directory back into the repo for the gradle wrapper scripts to work.  Also, you should probably reference them as `./gradlew` in the README since an experienced java dev who has gradle installed will know they can use `gradle` instead of `./gradlew`

**Comment by RadicalZephyr** [comment]
All that is to say, that no, the build script still doesn't work :p

**Comment by esmevane** [comment]
Whoops!  Easy enough to fix, at least.  Just rolled out https://github.com/esmevane/duckling/pull/9 - hopefully that helps!

**Comment by RadicalZephyr** [comment]
Almost there:

```
BUILD SUCCESSFUL

Total time: 31.633 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.13/userguide/gradle_daemon.html
geoff@airpad ~/src/duckling (master=) $ java ./duckling.jar
Error: Could not find or load main class ..duckling.jar
```

**Comment by esmevane** [comment]
Try this:

```bash
java -jar ./duckling.jar -p 5000 -d .
```

**Comment by trptcolin** [comment]
👍  that works, just needs the associated README update from your last comment to close this issue.

**Comment by RadicalZephyr** [comment]
You shouldn't need the preceding `./` fyi, but it doesn't hurt either

**Comment by esmevane** [comment]
Whoops!  I can't believe I didn't have the `-jar` info in the README.  Updated in https://github.com/esmevane/duckling/pull/11

**Comment by trptcolin** [comment]
👍
